### ISSUE TITLE
Best way to benchmark?

### ISSUE THREAD

**Issue by HammerMeetNail** [rancher/kine#35]
Hey, really like the tool. Any thoughts on the best way to benchmark so performance can be compared directly with etcd?

I'm having some success with  [etcd benchmark](https://github.com/etcd-io/etcd/tree/master/tools/benchmark), but since not everything is implemented only some of the tests complete. Anything that requires a `put` will fail. Thoughts?

```
$ benchmark watch
 1000 / 1000 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00% 0s
Watch creation summary:

Summary:
  Total:	0.1874 secs.
  Slowest:	0.0177 secs.
  Fastest:	0.0001 secs.
  Average:	0.0018 secs.
  Stddev:	0.0023 secs.
  Requests/sec:	5335.9095

Response time histogram:
  0.0001 [1]	|
  0.0019 [757]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.0036 [162]	|∎∎∎∎∎∎∎∎
  0.0054 [28]	|∎
  0.0072 [18]	|
  0.0089 [7]	|
  0.0107 [7]	|
  0.0124 [8]	|
  0.0142 [3]	|
  0.0160 [0]	|
  0.0177 [9]	|

Latency distribution:
  10% in 0.0005 secs.
  25% in 0.0008 secs.
  50% in 0.0012 secs.
  75% in 0.0019 secs.
  90% in 0.0029 secs.
  95% in 0.0054 secs.
  99% in 0.0125 secs.
  99.9% in 0.0177 secs.
 0 / 1000000 B                                                                                                                                                                                            !   0.00%{"level":"warn","ts":"2020-05-23T16:03:59.596-0400","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-a774489f-5514-4646-acaf-f9d93b860e8c/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unknown desc = put is not supported"}
panic: rpc error: code = Unknown desc = put is not supported

goroutine 2210 [running]:
go.etcd.io/etcd/tools/benchmark/cmd.benchPutWatches.func3(0xc000634480, 0xc00021cb90, 0xc0002289c0)
	/home/dave/go/src/go.etcd.io/etcd/tools/benchmark/cmd/watch.go:222 +0x1f9
created by go.etcd.io/etcd/tools/benchmark/cmd.benchPutWatches
	/home/dave/go/src/go.etcd.io/etcd/tools/benchmark/cmd/watch.go:216 +0x2d4
```

**Comment by galal-hussein** [comment]
@HammerMeetNail we did a bunch of performance tests from the k3s prespective with different sql backend databases, you might need to check the following https://github.com/rancher/k3s/tree/master/tests/perf

**Comment by HammerMeetNail** [comment]
Thanks, I'll take a look!
